export const sampleStudents =
  [
    {
      "id": 2,
      "program_id": 1500038,
      "registration_no": "O0325001",
      "application_no": "OLUGDS100019",
      "title": "12838",
      "first_name": "Jeswin",
      "last_name": "L",
      "gender": "12842",
      "date_of_birth": "2006-04-10",
      "blood_group": "1306",
      "email": "jeswinaro001@gmail.com",
      "mobile_number": "919626512494",
      "alternative_phone": null,
      "whatsapp_number": "+91-9626512494",
      "marital_status": "12855",
      "religion": "19203",
      "nationality": 101,
      "category": "1500034",
      "caste": "Nathaman",
      "aadhaar_number": "452268769783",
      "pan_number": "ATEPM2324D",
      "parent_guardian_name": "Luckas Antony Samy",
      "relationship_with_student": "1500059",
      "current_employment": null,
      "annual_income": null,
      "locality": "1500102",
      "passport_issued_country": null,
      "passport_number": null,
      "passport_expiry_date": null,
      "is_deleted": false,
      "created_at": "2025-08-28T06:46:49.126164",
      "updated_at": "2025-08-28T06:46:49.126167",
      "address_details": {
        "corr_addr1": "1446/C-1 Aro illam",
        "corr_addr2": "Annanagar",
        "corr_city": "32208",
        "corr_state": "32052",
        "corr_district": "32207",
        "corr_country": 101,
        "corr_pin": "630561",
        "corr_addr_same": true,
        "perm_addr1": "1446/C-1 Aro illam",
        "perm_addr2": "Annanagar",
        "perm_city": "32208",
        "perm_state": "32052",
        "perm_district": "32207",
        "perm_country": 101,
        "perm_pin": "630561",
        "id": 1
      },
      "academic_details": {
        "ssc_board_id": 12929,
        "ssc_school": "shri ramana vikass hr sec",
        "ssc_scheme": "Percentage",
        "ssc_score": "50",
        "ssc_year": "2020-12-31",
        "after_ssc": "Class XII/HSC",
        "hsc_board_id": 12964,
        "hsc_school": "shri ramana vikass hr sec",
        "hsc_result": "Declared",
        "hsc_scheme": "Percentage",
        "hsc_score": "73",
        "hsc_year": "2022-12-31",
        "diploma_institute": "",
        "diploma_board": "",
        "diploma_result": "",
        "diploma_scheme": "",
        "diploma_score": "",
        "diploma_year": null,
        "id": 2
      },
      "declaration_details": {
        "declaration_agreed": true,
        "applicant_name": "Jeswin L",
        "parent_name": "Luckas Antony Samy",
        "declaration_date": "2025-07-23",
        "place": "Sivaganga",
        "id": 1
      },
      "deb_details": {
        "deb_id": "072502723575",
        "deb_name": "AAKASH",
        "deb_gender": "Male",
        "deb_date_of_birth": "04/03/2006",
        "deb_university": null,
        "deb_program": null,
        "deb_abcid": "727709278961",
        "deb_details_1": null,
        "deb_details_2": null,
        "deb_details_3": null,
        "deb_details_4": null,
        "deb_details_5": null,
        "deb_details_6": null,
        "deb_details_7": null,
        "deb_details_8": null,
        "deb_details_9": null,
        "deb_details_10": null,
        "deb_details_11": null,
        "deb_details_12": null,
        "deb_details_13": null,
        "deb_details_14": null,
        "deb_details_15": null,
        "deb_status": "Success",
        "id": 1
      },
      "payments": [
        {
          "id": 2,
          "student_id": 2,
          "payment_type": "semester_fee",
          "order_id": "4517_912_7",
          "transaction_id": "1756104891",
          "payment_date": "2025-08-25T00:00:00",
          "payment_amount": 17750,
          "is_offline": false,
          "offline_transaction_id": null,
          "offline_payment_method": null,
          "offline_receipt_enabled": false,
          "application_fee": null,
          "semester_fee": {
            "id": 1,
            "payment_id": 2,
            "semester": "1st",
            "lab_fee": 0,
            "lms_fee": 0,
            "exam_fee": 0,
            "tuition_fee": 0,
            "total_fee": 0
          }
        }
      ]
    },
    {
      "id": 6,
      "program_id": 1500038,
      "registration_no": "O0325005",
      "application_no": "OLUGDS100071",
      "title": "12838",
      "first_name": "Abishek Kumaran",
      "last_name": "Balaji",
      "gender": "12842",
      "date_of_birth": "2005-11-06",
      "blood_group": "1311",
      "email": "abishekkumaranbalaji@gmail.com",
      "mobile_number": "918825972045",
      "alternative_phone": "+91-9445270270",
      "whatsapp_number": "+91-8825972045",
      "marital_status": "12855",
      "religion": "19201",
      "nationality": 101,
      "category": "1500034",
      "caste": "Nadar",
      "aadhaar_number": "293026572067",
      "pan_number": "HXUPB9889Q",
      "parent_guardian_name": "Balaji D",
      "relationship_with_student": "1500059",
      "current_employment": "1500055",
      "annual_income": "1500025",
      "locality": "1500102",
      "passport_issued_country": null,
      "passport_number": null,
      "passport_expiry_date": null,
      "is_deleted": false,
      "created_at": "2025-08-28T06:46:49.183119",
      "updated_at": "2025-08-28T06:46:49.183122",
      "address_details": {
        "corr_addr1": "9-119, 4th Street, Sai Nagar",
        "corr_addr2": "Virugambakkam",
        "corr_city": "32059",
        "corr_state": "32052",
        "corr_district": "32058",
        "corr_country": 101,
        "corr_pin": "600092",
        "corr_addr_same": true,
        "perm_addr1": "9-119, 4th Street, Sai Nagar",
        "perm_addr2": "Virugambakkam",
        "perm_city": "32059",
        "perm_state": "32052",
        "perm_district": "32058",
        "perm_country": 101,
        "perm_pin": "600092",
        "id": 5
      },
      "academic_details": {
        "ssc_board_id": 12901,
        "ssc_school": "DEVI ACADEMY SENIOR SECONDARY SCHOOL",
        "ssc_scheme": "Percentage",
        "ssc_score": "94.4",
        "ssc_year": "2021-12-31",
        "after_ssc": "Class XII/HSC",
        "hsc_board_id": 12937,
        "hsc_school": "THE VELAMMAL INTERNATIONAL SCHOOL",
        "hsc_result": "Declared",
        "hsc_scheme": "Percentage",
        "hsc_score": "91.2",
        "hsc_year": "2023-12-31",
        "diploma_institute": "",
        "diploma_board": "",
        "diploma_result": "",
        "diploma_scheme": "",
        "diploma_score": "",
        "diploma_year": null,
        "id": 6
      },
      "declaration_details": {
        "declaration_agreed": true,
        "applicant_name": "Abishek Kumaran Balaji",
        "parent_name": "Balaji D",
        "declaration_date": "2025-08-12",
        "place": "Chennai",
        "id": 5
      },
      "deb_details": {
        "deb_id": "082503087698",
        "deb_name": "ABISHEK KUMARAN BALAJI",
        "deb_gender": "Male",
        "deb_date_of_birth": "07/11/2005",
        "deb_university": null,
        "deb_program": null,
        "deb_abcid": "618114525529",
        "deb_details_1": null,
        "deb_details_2": null,
        "deb_details_3": null,
        "deb_details_4": null,
        "deb_details_5": null,
        "deb_details_6": null,
        "deb_details_7": null,
        "deb_details_8": null,
        "deb_details_9": null,
        "deb_details_10": null,
        "deb_details_11": null,
        "deb_details_12": null,
        "deb_details_13": null,
        "deb_details_14": null,
        "deb_details_15": null,
        "deb_status": "Success",
        "id": 5
      },
      "payments": [
        {
          "id": 7,
          "student_id": 6,
          "payment_type": "semester_fee",
          "order_id": "4034_912_7",
          "transaction_id": "pay_R7ACWI4s7UGFd1",
          "payment_date": "2025-08-19T00:00:00",
          "payment_amount": 17750,
          "is_offline": false,
          "offline_transaction_id": null,
          "offline_payment_method": null,
          "offline_receipt_enabled": false,
          "application_fee": null,
          "semester_fee": {
            "id": 2,
            "payment_id": 7,
            "semester": "1st",
            "lab_fee": 2000,
            "lms_fee": 500,
            "exam_fee": 500,
            "tuition_fee": 13750,
            "total_fee": 17750
          }
        },
        {
          "id": 6,
          "student_id": 6,
          "payment_type": "application_fee",
          "order_id": "4032_912_7",
          "transaction_id": "pay_R79u9W4ZOfeUHQ",
          "payment_date": "2025-08-19T00:00:00",
          "payment_amount": 500,
          "is_offline": false,
          "offline_transaction_id": null,
          "offline_payment_method": null,
          "offline_receipt_enabled": false,
          "application_fee": {
            "id": 4,
            "payment_id": 6
          },
          "semester_fee": null
        }
      ]
    },
    {
      "id": 7,
      "program_id": 1500038,
      "registration_no": "O0325006",
      "application_no": "OLUGDS100128",
      "title": "12838",
      "first_name": "Adhithya",
      "last_name": "N. S. G.",
      "gender": "12842",
      "date_of_birth": "2004-11-30",
      "blood_group": "1306",
      "email": "rudhras2008@gmail.com",
      "mobile_number": "919600077002",
      "alternative_phone": "+91-7092295079",
      "whatsapp_number": "+91-9600077002",
      "marital_status": "12855",
      "religion": "19201",
      "nationality": 101,
      "category": "1500034",
      "caste": null,
      "aadhaar_number": "251855013610",
      "pan_number": "EQUPG1982F",
      "parent_guardian_name": "Ganesh moorthy. N. S",
      "relationship_with_student": "1500059",
      "current_employment": null,
      "annual_income": null,
      "locality": "1500102",
      "passport_issued_country": null,
      "passport_number": null,
      "passport_expiry_date": null,
      "is_deleted": false,
      "created_at": "2025-09-12T04:56:54.737323",
      "updated_at": "2025-09-12T04:56:54.737326",
      "address_details": {
        "corr_addr1": "33and34 Radha nagar main road",
        "corr_addr2": "Valasaravakkam chennai",
        "corr_city": "32059",
        "corr_state": "32052",
        "corr_district": "32058",
        "corr_country": 101,
        "corr_pin": "600087",
        "corr_addr_same": true,
        "perm_addr1": "33and34 Radha nagar main road",
        "perm_addr2": "Valasaravakkam chennai",
        "perm_city": "32059",
        "perm_state": "32052",
        "perm_district": "32058",
        "perm_country": 101,
        "perm_pin": "600087",
        "id": 6
      },
      "academic_details": {
        "ssc_board_id": 12901,
        "ssc_school": "PON VIDYASHRAM",
        "ssc_scheme": "Percentage",
        "ssc_score": "72",
        "ssc_year": "2019-12-31",
        "after_ssc": "Class XII/HSC",
        "hsc_board_id": 12937,
        "hsc_school": "PON VIDYASHRAM",
        "hsc_result": "Declared",
        "hsc_scheme": "Percentage",
        "hsc_score": "75.2",
        "hsc_year": "2021-12-31",
        "diploma_institute": "",
        "diploma_board": "",
        "diploma_result": "",
        "diploma_scheme": "",
        "diploma_score": "",
        "diploma_year": null,
        "id": 7
      },
      "declaration_details": {
        "declaration_agreed": true,
        "applicant_name": "Adhithya N. S. G.",
        "parent_name": "GANESHMOORTHY N S",
        "declaration_date": "2025-08-17",
        "place": "CHENNAI",
        "id": 6
      },
      "deb_details": {
        "deb_id": "082503196013",
        "deb_name": "Adhithya N S G",
        "deb_gender": "Male",
        "deb_date_of_birth": "01/12/2004",
        "deb_university": null,
        "deb_program": null,
        "deb_abcid": "326462710092",
        "deb_details_1": null,
        "deb_details_2": null,
        "deb_details_3": null,
        "deb_details_4": null,
        "deb_details_5": null,
        "deb_details_6": null,
        "deb_details_7": null,
        "deb_details_8": null,
        "deb_details_9": null,
        "deb_details_10": null,
        "deb_details_11": null,
        "deb_details_12": null,
        "deb_details_13": null,
        "deb_details_14": null,
        "deb_details_15": null,
        "deb_status": "Success",
        "id": 6
      },
      "payments": [
        {
          "id": 9,
          "student_id": 7,
          "payment_type": "semester_fee",
          "order_id": "4736_912_7",
          "transaction_id": "pay_RAMuDfJeLap1zI",
          "payment_date": "2025-08-27T00:00:00",
          "payment_amount": 17750,
          "is_offline": false,
          "offline_transaction_id": null,
          "offline_payment_method": null,
          "offline_receipt_enabled": false,
          "application_fee": null,
          "semester_fee": {
            "id": 3,
            "payment_id": 9,
            "semester": "1st",
            "lab_fee": 0,
            "lms_fee": 0,
            "exam_fee": 0,
            "tuition_fee": 0,
            "total_fee": 0
          }
        },
        {
          "id": 8,
          "student_id": 7,
          "payment_type": "application_fee",
          "order_id": "4043_912_7",
          "transaction_id": "pay_R7Bqqmhykbmlzn",
          "payment_date": "2025-08-19T00:00:00",
          "payment_amount": 500,
          "is_offline": false,
          "offline_transaction_id": null,
          "offline_payment_method": null,
          "offline_receipt_enabled": false,
          "application_fee": {
            "id": 5,
            "payment_id": 8
          },
          "semester_fee": null
        }
      ]
    },
    {
      "id": 8,
      "program_id": 1500038,
      "registration_no": "O0325007",
      "application_no": "OLUGDS100289",
      "title": "12840",
      "first_name": "Manimekalai",
      "last_name": "Narayanan",
      "gender": "12843",
      "date_of_birth": "1985-05-31",
      "blood_group": "1308",
      "email": "m.manimekalai@sriramachandra.edu.in",
      "mobile_number": "919841368740",
      "alternative_phone": "+91-9094751818",
      "whatsapp_number": "+91-9841368740",
      "marital_status": "12856",
      "religion": "19201",
      "nationality": 101,
      "category": "1500034",
      "caste": "Thuluva vellar",
      "aadhaar_number": "568762655262",
      "pan_number": "AXZPM2307G",
      "parent_guardian_name": "NARAYANAN V",
      "relationship_with_student": "1500061",
      "current_employment": "1500056",
      "annual_income": "1500027",
      "locality": "1500102",
      "passport_issued_country": null,
      "passport_number": null,
      "passport_expiry_date": null,
      "is_deleted": false,
      "created_at": "2025-09-12T04:56:54.759570",
      "updated_at": "2025-09-12T04:56:54.759574",
      "address_details": {
        "corr_addr1": "Balakrishna Nagar, Sundharasozhavaram",
        "corr_addr2": "Thiruverkadu",
        "corr_city": "32059",
        "corr_state": "32052",
        "corr_district": "32058",
        "corr_country": 101,
        "corr_pin": "600077",
        "corr_addr_same": true,
        "perm_addr1": "Balakrishna Nagar, Sundharasozhavaram",
        "perm_addr2": "Thiruverkadu",
        "perm_city": "32059",
        "perm_state": "32052",
        "perm_district": "32058",
        "perm_country": 101,
        "perm_pin": "600077",
        "id": 7
      },
      "academic_details": {
        "ssc_board_id": 12929,
        "ssc_school": "Sekkizhar Governmen Girls High school",
        "ssc_scheme": "Percentage",
        "ssc_score": "61",
        "ssc_year": "1999-12-31",
        "after_ssc": "Class XII/HSC",
        "hsc_board_id": 12964,
        "hsc_school": "Sekkizhar Government High School",
        "hsc_result": "Declared",
        "hsc_scheme": "Percentage",
        "hsc_score": "61",
        "hsc_year": "2001-12-31",
        "diploma_institute": "",
        "diploma_board": "",
        "diploma_result": "",
        "diploma_scheme": "",
        "diploma_score": "",
        "diploma_year": null,
        "id": 8
      },
      "declaration_details": {
        "declaration_agreed": true,
        "applicant_name": "Manimekalai Narayanan",
        "parent_name": "NarayananV",
        "declaration_date": "2025-08-31",
        "place": "Chennai",
        "id": 7
      },
      "deb_details": {
        "deb_id": "092503389696",
        "deb_name": "Manimekalai N",
        "deb_gender": "Female",
        "deb_date_of_birth": "01/06/1985",
        "deb_university": null,
        "deb_program": null,
        "deb_abcid": "644827974230",
        "deb_details_1": null,
        "deb_details_2": null,
        "deb_details_3": null,
        "deb_details_4": null,
        "deb_details_5": null,
        "deb_details_6": null,
        "deb_details_7": null,
        "deb_details_8": null,
        "deb_details_9": null,
        "deb_details_10": null,
        "deb_details_11": null,
        "deb_details_12": null,
        "deb_details_13": null,
        "deb_details_14": null,
        "deb_details_15": null,
        "deb_status": "Success",
        "id": 7
      },
      "payments": [
        {
          "id": 11,
          "student_id": 8,
          "payment_type": "semester_fee",
          "order_id": "4895_912_7",
          "transaction_id": "pay_RCya1ciFhSLlwQ",
          "payment_date": "2025-09-03T00:00:00",
          "payment_amount": 17750,
          "is_offline": false,
          "offline_transaction_id": null,
          "offline_payment_method": null,
          "offline_receipt_enabled": false,
          "application_fee": null,
          "semester_fee": {
            "id": 4,
            "payment_id": 11,
            "semester": "1st",
            "lab_fee": 0,
            "lms_fee": 0,
            "exam_fee": 0,
            "tuition_fee": 0,
            "total_fee": 0
          }
        },
        {
          "id": 10,
          "student_id": 8,
          "payment_type": "application_fee",
          "order_id": "4846_912_7",
          "transaction_id": "pay_RCGtNzFdmgeorL",
          "payment_date": "2025-09-01T00:00:00",
          "payment_amount": 500,
          "is_offline": false,
          "offline_transaction_id": null,
          "offline_payment_method": null,
          "offline_receipt_enabled": false,
          "application_fee": {
            "id": 6,
            "payment_id": 10
          },
          "semester_fee": null
        }
      ]
    },
    {
      "id": 9,
      "program_id": 1500038,
      "registration_no": "O0325008",
      "application_no": "OLUGDS100290",
      "title": "12838",
      "first_name": "Ramkumar",
      "last_name": "Santhanakrishnan",
      "gender": "12842",
      "date_of_birth": "1982-12-24",
      "blood_group": "1304",
      "email": "ramsipl21@gmail.com",
      "mobile_number": "918610371396",
      "alternative_phone": null,
      "whatsapp_number": "+91-8610371396",
      "marital_status": "12856",
      "religion": "19201",
      "nationality": 101,
      "category": "1500034",
      "caste": "Kamma Naidu",
      "aadhaar_number": "826660590404",
      "pan_number": "CJDPR7307F",
      "parent_guardian_name": "Murugaveni",
      "relationship_with_student": "1500062",
      "current_employment": "1500056",
      "annual_income": "1500029",
      "locality": "1500102",
      "passport_issued_country": null,
      "passport_number": null,
      "passport_expiry_date": null,
      "is_deleted": false,
      "created_at": "2025-09-12T06:34:26.275164",
      "updated_at": "2025-09-12T06:34:26.275167",
      "address_details": {
        "corr_addr1": "526 Sree Sai Kuteera Appts  , 3rd Floor ,",
        "corr_addr2": "Lakke gowda nagar , BHCS Layout",
        "corr_city": "35207",
        "corr_state": "29881",
        "corr_district": "29922",
        "corr_country": 101,
        "corr_pin": "560061",
        "corr_addr_same": true,
        "perm_addr1": "526 Sree Sai Kuteera Appts  , 3rd Floor ,",
        "perm_addr2": "Lakke gowda nagar , BHCS Layout",
        "perm_city": "35207",
        "perm_state": "29881",
        "perm_district": "29922",
        "perm_country": 101,
        "perm_pin": "560061",
        "id": 8
      },
      "academic_details": {
        "ssc_board_id": 12929,
        "ssc_school": "MCNUP DA HSS",
        "ssc_scheme": "Percentage",
        "ssc_score": "71",
        "ssc_year": "1998-12-31",
        "after_ssc": "Diploma",
        "hsc_board_id": null,
        "hsc_school": "",
        "hsc_result": "",
        "hsc_scheme": "",
        "hsc_score": "",
        "hsc_year": null,
        "diploma_institute": "JACSI Polytechnic",
        "diploma_board": "State board of Technical Education",
        "diploma_result": "Declared",
        "diploma_scheme": "Percentage",
        "diploma_score": "58",
        "diploma_year": "2001-12-31",
        "id": 9
      },
      "declaration_details": {
        "declaration_agreed": true,
        "applicant_name": "Ramkumar Santhanakrishnan",
        "parent_name": "Santhanakrishnan",
        "declaration_date": "2025-08-28",
        "place": "Bangalore",
        "id": 8
      },
      "deb_details": {
        "deb_id": "0925035465391",
        "deb_name": "Ramkumar",
        "deb_gender": "Male",
        "deb_date_of_birth": "25/12/1982",
        "deb_university": null,
        "deb_program": null,
        "deb_abcid": "300148436977",
        "deb_details_1": null,
        "deb_details_2": null,
        "deb_details_3": null,
        "deb_details_4": null,
        "deb_details_5": null,
        "deb_details_6": null,
        "deb_details_7": null,
        "deb_details_8": null,
        "deb_details_9": null,
        "deb_details_10": null,
        "deb_details_11": null,
        "deb_details_12": null,
        "deb_details_13": null,
        "deb_details_14": null,
        "deb_details_15": null,
        "deb_status": "Success",
        "id": 8
      },
      "payments": [
        {
          "id": 13,
          "student_id": 9,
          "payment_type": "semester_fee",
          "order_id": "4925_912_7",
          "transaction_id": "pay_RDPOpx7Bgv7bgw",
          "payment_date": "2025-09-04T00:00:00",
          "payment_amount": 17750,
          "is_offline": false,
          "offline_transaction_id": null,
          "offline_payment_method": null,
          "offline_receipt_enabled": false,
          "application_fee": null,
          "semester_fee": {
            "id": 5,
            "payment_id": 13,
            "semester": "1st",
            "lab_fee": 0,
            "lms_fee": 0,
            "exam_fee": 0,
            "tuition_fee": 0,
            "total_fee": 0
          }
        },
        {
          "id": 12,
          "student_id": 9,
          "payment_type": "application_fee",
          "order_id": "4923_912_7",
          "transaction_id": "pay_RDP9A7gNoHG2f1",
          "payment_date": "2025-09-04T00:00:00",
          "payment_amount": 500,
          "is_offline": false,
          "offline_transaction_id": null,
          "offline_payment_method": null,
          "offline_receipt_enabled": false,
          "application_fee": {
            "id": 7,
            "payment_id": 12
          },
          "semester_fee": null
        }
      ]
    },
    {
      "id": 10,
      "program_id": 1500038,
      "registration_no": "O0325009",
      "application_no": "OLUGDS100319",
      "title": "12838",
      "first_name": "Aswin",
      "last_name": "T",
      "gender": "12842",
      "date_of_birth": "2006-06-20",
      "blood_group": "1306",
      "email": "thangarajuaswin123@gmail.com",
      "mobile_number": "916374271166",
      "alternative_phone": "+91-9524133915",
      "whatsapp_number": "+91-6374271166",
      "marital_status": "12855",
      "religion": "19201",
      "nationality": 101,
      "category": "1500035",
      "caste": "Devendra Kula velalar",
      "aadhaar_number": "840036295578",
      "pan_number": "CUYPT6608R",
      "parent_guardian_name": "T. Vasanthi",
      "relationship_with_student": "1500060",
      "current_employment": "1500057",
      "annual_income": "1500025",
      "locality": "1500103",
      "passport_issued_country": null,
      "passport_number": null,
      "passport_expiry_date": null,
      "is_deleted": false,
      "created_at": "2025-09-12T06:34:26.297057",
      "updated_at": "2025-09-12T06:34:26.297060",
      "address_details": {
        "corr_addr1": "1/258, shanmuga nagar, bharat nagar, road, poolangudi colony, happ post, trichy-25",
        "corr_addr2": "1/258, shanmuga nagar, bharat nagar road, poolangudi colony, HAPP post, trichy-25",
        "corr_city": "32244",
        "corr_state": "32052",
        "corr_district": "32243",
        "corr_country": 101,
        "corr_pin": "620025",
        "corr_addr_same": true,
        "perm_addr1": "1/258, shanmuga nagar, bharat nagar, road, poolangudi colony, happ post, trichy-25",
        "perm_addr2": "1/258, shanmuga nagar, bharat nagar road, poolangudi colony, HAPP post, trichy-25",
        "perm_city": "32244",
        "perm_state": "32052",
        "perm_district": "32243",
        "perm_country": 101,
        "perm_pin": "620025",
        "id": 9
      },
      "academic_details": {
        "ssc_board_id": 12901,
        "ssc_school": "PM SHRI KENDRIYA VIDYALAYA NO.1, TRICHY-16",
        "ssc_scheme": "Percentage",
        "ssc_score": "78.8",
        "ssc_year": "2021-12-31",
        "after_ssc": "Class XII/HSC",
        "hsc_board_id": 12937,
        "hsc_school": "PM SHRI KENDRIYA VIDYALAYA NO.1, TRICHY-16",
        "hsc_result": "Declared",
        "hsc_scheme": "Percentage",
        "hsc_score": "63.40",
        "hsc_year": "2023-12-31",
        "diploma_institute": "",
        "diploma_board": "",
        "diploma_result": "",
        "diploma_scheme": "",
        "diploma_score": "",
        "diploma_year": null,
        "id": 10
      },
      "declaration_details": {
        "declaration_agreed": true,
        "applicant_name": "Aswin T",
        "parent_name": "T VASANTHI",
        "declaration_date": "2025-08-31",
        "place": "TIRUCHIRAPALLI",
        "id": 9
      },
      "deb_details": {
        "deb_id": "092503408680",
        "deb_name": "T ASWIN",
        "deb_gender": "Male",
        "deb_date_of_birth": "21/06/2006",
        "deb_university": null,
        "deb_program": null,
        "deb_abcid": "149951282698",
        "deb_details_1": null,
        "deb_details_2": null,
        "deb_details_3": null,
        "deb_details_4": null,
        "deb_details_5": null,
        "deb_details_6": null,
        "deb_details_7": null,
        "deb_details_8": null,
        "deb_details_9": null,
        "deb_details_10": null,
        "deb_details_11": null,
        "deb_details_12": null,
        "deb_details_13": null,
        "deb_details_14": null,
        "deb_details_15": null,
        "deb_status": "Success",
        "id": 9
      },
      "payments": [
        {
          "id": 15,
          "student_id": 10,
          "payment_type": "semester_fee",
          "order_id": "4866_912_7",
          "transaction_id": "pay_RCcCLKGpKDMtBu",
          "payment_date": "2025-09-02T00:00:00",
          "payment_amount": 17750,
          "is_offline": false,
          "offline_transaction_id": null,
          "offline_payment_method": null,
          "offline_receipt_enabled": false,
          "application_fee": null,
          "semester_fee": {
            "id": 6,
            "payment_id": 15,
            "semester": "1st",
            "lab_fee": 0,
            "lms_fee": 0,
            "exam_fee": 0,
            "tuition_fee": 0,
            "total_fee": 0
          }
        },
        {
          "id": 14,
          "student_id": 10,
          "payment_type": "application_fee",
          "order_id": "4865_912_7",
          "transaction_id": "pay_RCbxpzZJRLFFY6",
          "payment_date": "2025-09-02T00:00:00",
          "payment_amount": 500,
          "is_offline": false,
          "offline_transaction_id": null,
          "offline_payment_method": null,
          "offline_receipt_enabled": false,
          "application_fee": {
            "id": 8,
            "payment_id": 14
          },
          "semester_fee": null
        }
      ]
    },
    {
      "id": 5,
      "program_id": 1500038,
      "registration_no": "O0325004",
      "application_no": "OLUGDS100034",
      "title": "12838",
      "first_name": "mohammed afrid",
      "last_name": "azami",
      "gender": "12842",
      "date_of_birth": "2007-04-13",
      "blood_group": "1308",
      "email": "afridazami14@gmail.com",
      "mobile_number": "919840956360",
      "alternative_phone": null,
      "whatsapp_number": "+91-9840956360",
      "marital_status": "12855",
      "religion": "19202",
      "nationality": 101,
      "category": "1500034",
      "caste": null,
      "aadhaar_number": "285152408816",
      "pan_number": "ATEPT8687D",
      "parent_guardian_name": "mohammed kaifi azami",
      "relationship_with_student": "1500059",
      "current_employment": "1500055",
      "annual_income": "1500025",
      "locality": "1500102",
      "passport_issued_country": null,
      "passport_number": null,
      "passport_expiry_date": null,
      "is_deleted": false,
      "created_at": "2025-08-28T06:46:49.174842",
      "updated_at": "2025-08-28T06:46:49.174844",
      "address_details": {
        "corr_addr1": "18/3,39/4 subedar hussain street royapettah",
        "corr_addr2": null,
        "corr_city": "32059",
        "corr_state": "32052",
        "corr_district": "32058",
        "corr_country": 101,
        "corr_pin": "600014",
        "corr_addr_same": true,
        "perm_addr1": "18/3,39/4 subedar hussain street royapettah",
        "perm_addr2": null,
        "perm_city": "32059",
        "perm_state": "32052",
        "perm_district": "32058",
        "perm_country": 101,
        "perm_pin": "600014",
        "id": 4
      },
      "academic_details": {
        "ssc_board_id": 12901,
        "ssc_school": "dav boys sr sec school",
        "ssc_scheme": "Percentage",
        "ssc_score": "55",
        "ssc_year": "2022-12-31",
        "after_ssc": "Class XII/HSC",
        "hsc_board_id": 12964,
        "hsc_school": "sree venkateshwa matric hr sec school",
        "hsc_result": "Declared",
        "hsc_scheme": "Percentage",
        "hsc_score": "71",
        "hsc_year": "2024-12-31",
        "diploma_institute": "",
        "diploma_board": "",
        "diploma_result": "",
        "diploma_scheme": "",
        "diploma_score": "",
        "diploma_year": null,
        "id": 5
      },
      "declaration_details": {
        "declaration_agreed": true,
        "applicant_name": "mohammed afrid azami",
        "parent_name": "mohammed kaifi azami",
        "declaration_date": "2025-08-07",
        "place": "chennai",
        "id": 4
      },
      "deb_details": {
        "deb_id": "0825030",
        "deb_name": null,
        "deb_gender": null,
        "deb_date_of_birth": null,
        "deb_university": null,
        "deb_program": null,
        "deb_abcid": null,
        "deb_details_1": null,
        "deb_details_2": null,
        "deb_details_3": null,
        "deb_details_4": null,
        "deb_details_5": null,
        "deb_details_6": null,
        "deb_details_7": null,
        "deb_details_8": null,
        "deb_details_9": null,
        "deb_details_10": null,
        "deb_details_11": null,
        "deb_details_12": null,
        "deb_details_13": null,
        "deb_details_14": null,
        "deb_details_15": null,
        "deb_status": "Failed",
        "id": 4
      },
      "payments": [
        {
          "id": 5,
          "student_id": 5,
          "payment_type": "application_fee",
          "order_id": "2655_912_7",
          "transaction_id": "pay_R2mqwAxs4N6uD0",
          "payment_date": "2025-08-08T00:00:00",
          "payment_amount": 500,
          "is_offline": false,
          "offline_transaction_id": null,
          "offline_payment_method": null,
          "offline_receipt_enabled": false,
          "application_fee": {
            "id": 3,
            "payment_id": 5
          },
          "semester_fee": null
        }
      ]
    },
    {
      "id": 4,
      "program_id": 1500038,
      "registration_no": "O0325003",
      "application_no": "OLUGDS100033",
      "title": "12838",
      "first_name": "Kaushal",
      "last_name": "Shanker",
      "gender": "12842",
      "date_of_birth": "2003-10-31",
      "blood_group": "1308",
      "email": "shankerkaushal03@gmail.com",
      "mobile_number": "919444506363",
      "alternative_phone": null,
      "whatsapp_number": "+91-9444506363",
      "marital_status": "12855",
      "religion": "19201",
      "nationality": 101,
      "category": "1500034",
      "caste": null,
      "aadhaar_number": "258299310199",
      "pan_number": "LQZPK1778F",
      "parent_guardian_name": "De.Hemalatha shanker",
      "relationship_with_student": "1500060",
      "current_employment": "1500055",
      "annual_income": "1500025",
      "locality": "1500102",
      "passport_issued_country": null,
      "passport_number": null,
      "passport_expiry_date": null,
      "is_deleted": false,
      "created_at": "2025-08-28T06:46:49.165731",
      "updated_at": "2025-08-28T06:46:49.165734",
      "address_details": {
        "corr_addr1": "Chendur house ,F-114,5th stree",
        "corr_addr2": "Annanagar east , chennai",
        "corr_city": "32059",
        "corr_state": "32052",
        "corr_district": "32058",
        "corr_country": 101,
        "corr_pin": "600102",
        "corr_addr_same": true,
        "perm_addr1": "Chendur house ,F-114,5th stree",
        "perm_addr2": "Annanagar east , chennai",
        "perm_city": "32059",
        "perm_state": "32052",
        "perm_district": "32058",
        "perm_country": 101,
        "perm_pin": "600102",
        "id": 3
      },
      "academic_details": {
        "ssc_board_id": 12901,
        "ssc_school": "SBOA",
        "ssc_scheme": "Percentage",
        "ssc_score": "80",
        "ssc_year": "2018-12-31",
        "after_ssc": "Class XII/HSC",
        "hsc_board_id": 12937,
        "hsc_school": "Saraswathi vidyalaya",
        "hsc_result": "Declared",
        "hsc_scheme": "CGPA out of 10",
        "hsc_score": "7.3",
        "hsc_year": "2020-12-31",
        "diploma_institute": "",
        "diploma_board": "",
        "diploma_result": "",
        "diploma_scheme": "",
        "diploma_score": "",
        "diploma_year": null,
        "id": 4
      },
      "declaration_details": {
        "declaration_agreed": true,
        "applicant_name": "Kaushal Shanker",
        "parent_name": "DR.Hemalatha Shanker",
        "declaration_date": "2025-08-07",
        "place": "chennai",
        "id": 3
      },
      "deb_details": {
        "deb_id": "082503014252",
        "deb_name": null,
        "deb_gender": null,
        "deb_date_of_birth": null,
        "deb_university": null,
        "deb_program": null,
        "deb_abcid": null,
        "deb_details_1": null,
        "deb_details_2": null,
        "deb_details_3": null,
        "deb_details_4": null,
        "deb_details_5": null,
        "deb_details_6": null,
        "deb_details_7": null,
        "deb_details_8": null,
        "deb_details_9": null,
        "deb_details_10": null,
        "deb_details_11": null,
        "deb_details_12": null,
        "deb_details_13": null,
        "deb_details_14": null,
        "deb_details_15": null,
        "deb_status": "Failed",
        "id": 3
      },
      "payments": [
        {
          "id": 4,
          "student_id": 4,
          "payment_type": "application_fee",
          "order_id": "2640_912_7",
          "transaction_id": "pay_R2kwk6KjoKuoex",
          "payment_date": "2025-08-08T00:00:00",
          "payment_amount": 500,
          "is_offline": false,
          "offline_transaction_id": null,
          "offline_payment_method": null,
          "offline_receipt_enabled": false,
          "application_fee": {
            "id": 2,
            "payment_id": 4
          },
          "semester_fee": null
        }
      ]
    },
    {
      "id": 3,
      "program_id": 1500038,
      "registration_no": "O0325002",
      "application_no": "OLUGDS100028",
      "title": "12840",
      "first_name": "Dr Leena",
      "last_name": "Pavitha",
      "gender": "12843",
      "date_of_birth": "1993-08-27",
      "blood_group": "1306",
      "email": "leenapavitha28@gmail.com",
      "mobile_number": "919952385693",
      "alternative_phone": null,
      "whatsapp_number": "+91-9952385693",
      "marital_status": "12856",
      "religion": "19203",
      "nationality": 101,
      "category": "1500034",
      "caste": null,
      "aadhaar_number": "927311520557",
      "pan_number": "APDPL4470P",
      "parent_guardian_name": "Devadoss Salem Dinakar",
      "relationship_with_student": "1500061",
      "current_employment": "1500056",
      "annual_income": "1500026",
      "locality": "1500102",
      "passport_issued_country": null,
      "passport_number": null,
      "passport_expiry_date": null,
      "is_deleted": false,
      "created_at": "2025-08-28T06:46:49.155175",
      "updated_at": "2025-08-28T06:46:49.155178",
      "address_details": {
        "corr_addr1": "No 77 Subham apartments Gandhi nagar Adyar",
        "corr_addr2": null,
        "corr_city": "32059",
        "corr_state": "32052",
        "corr_district": "32058",
        "corr_country": 101,
        "corr_pin": "600020",
        "corr_addr_same": true,
        "perm_addr1": "No 77 Subham apartments Gandhi nagar Adyar",
        "perm_addr2": null,
        "perm_city": "32059",
        "perm_state": "32052",
        "perm_district": "32058",
        "perm_country": 101,
        "perm_pin": "600020",
        "id": 2
      },
      "academic_details": {
        "ssc_board_id": 12929,
        "ssc_school": "St Michael academy",
        "ssc_scheme": "Percentage",
        "ssc_score": "72",
        "ssc_year": "2007-12-31",
        "after_ssc": "Class XII/HSC",
        "hsc_board_id": 12964,
        "hsc_school": "St Michael academy",
        "hsc_result": "Declared",
        "hsc_scheme": "Percentage",
        "hsc_score": "67",
        "hsc_year": "2009-12-31",
        "diploma_institute": "",
        "diploma_board": "",
        "diploma_result": "",
        "diploma_scheme": "",
        "diploma_score": "",
        "diploma_year": null,
        "id": 3
      },
      "declaration_details": {
        "declaration_agreed": true,
        "applicant_name": "Dr Leena Pavitha",
        "parent_name": null,
        "declaration_date": "2025-08-05",
        "place": "Chennai",
        "id": 2
      },
      "deb_details": {
        "deb_id": "082502990589",
        "deb_name": "Leena Pavitha P",
        "deb_gender": "F",
        "deb_date_of_birth": "28/08/1993",
        "deb_university": null,
        "deb_program": null,
        "deb_abcid": "601599845755",
        "deb_details_1": null,
        "deb_details_2": null,
        "deb_details_3": null,
        "deb_details_4": null,
        "deb_details_5": null,
        "deb_details_6": null,
        "deb_details_7": null,
        "deb_details_8": null,
        "deb_details_9": null,
        "deb_details_10": null,
        "deb_details_11": null,
        "deb_details_12": null,
        "deb_details_13": null,
        "deb_details_14": null,
        "deb_details_15": null,
        "deb_status": "Success",
        "id": 2
      },
      "payments": [
        {
          "id": 3,
          "student_id": 3,
          "payment_type": "application_fee",
          "order_id": "2385_912_7",
          "transaction_id": "pay_R24ILMSvsHSujj",
          "payment_date": "2025-08-06T00:00:00",
          "payment_amount": 500,
          "is_offline": false,
          "offline_transaction_id": null,
          "offline_payment_method": null,
          "offline_receipt_enabled": false,
          "application_fee": {
            "id": 1,
            "payment_id": 3
          },
          "semester_fee": null
        }
      ]
    }
  ]