// export const BASE_URL = 'https://api.sriramachandradigilearn.edu.in/';
export const BASE_URL = 'https://uat-api.sriramachandradigilearn.edu.in/';
export const ApiRoutes = {
  LOGIN: '/auth/login',
  REGISTER: '/auth/register',
  USERS: '/users',
  PRODUCTS: '/products',
  GETSTUDENTSLIST:'/student/list',
  GETSTUDENTBYID:'student',
  STUDENTSYNC:'student/sync',
  PUSHTODEBL:'push/ugc',
  GETPROGRAMLIST:'programe/list',
  PROGRAMADD:'programe/add',
  PROGRAMFETCH:'programe',
  PROGRAMUPDATE:'programe/update',
  BULKADD:'user/bulk-add',
  GETSTUDENTFEES:'student/fees',
  CHANGEPASSWORD:'user/change-password',
  GETFACULTYLIST:'faculty/list',
  FACULTYADD:'faculty/add',
  GETSYLLABUSLIST:'faculty/list',
  SYLLABUSADD:'master/syllabus/add',
  COURSECODELIST:'master/coursecode/list',
  COURSECATEGORYLIST:'master/coursecategory/list',
  COURSETITLELIST:'master/coursetitle/list',
  COURSECODEADD:'master/coursecode/add',
  COURSECATEGORYADD:'master/coursecategory/add',
  COURSETITLEADD:'master/coursetitle/add',
};