// export const BASE_URL = 'https://api.sriramachandradigilearn.edu.in/';
export const BASE_URL = 'https://uat-api.sriramachandradigilearn.edu.in/';
export const ApiRoutes = {
  LOGIN: '/auth/login',
  REGISTER: '/auth/register',
  USERS: '/users',
  PRODUCTS: '/products',
  GETSTUDENTSLIST:'/student/list',
  GETSTUDENTBYID:'student',
  STUDENTSYNC:'student/sync',
  PUSHTODEBL:'push/ugc',
  GETPROGRAMLIST:'programe/list',
  PROGRAMADD:'programe/add',
  PROGRAMFETCH:'programe',
  PROGRAMUPDATE:'programe/update',
  BULKADD:'user/bulk-add',
  GETSTUDENTFEES:'student/fees',
  CHANGEPASSWORD:'user/change-password',
  GETFACULTYLIST:'staff/list',
  FACULTYADD:'staff/add',
  GETFACULTYBYID:'staff',
  GETSYLLABUSLIST:'syllabus/list',
  SYLLABUSADD:'syllabus/add',
  COURSECODELIST:'coursecode/list',
  COURSECATEGORYLIST:'coursecategory/list',
  COURSETITLELIST:'coursetitle/list',
  COURSECODEADD:'coursecode/add',
  COURSECATEGORYADD:'coursecategory/add',
  COURSETITLEADD:'coursetitle/add',
  GETROLES:'admin/roles',
  ROLESADD:'admin/roles/add',
  DELETEROLE:'admin/delete',
  ROLESUPDATE:'admin/update',
  GETDEPARTMENTS:'department/list',
  DEPARTMENTADD:'department/add',
  DEPARTMENTUPDATE:'department/update',
  DEPARTMENTDELETE:'department/delete',
  GETDEPARTMENTBYID:'department',
  SCHEMES:'schemes',
  SEMESTERS:'semesters',
  COURSES:'courses',
  COURSE_COMPONENTS:'course-components',
};