"""initial migrations

Revision ID: 0520308b8c6d
Revises: 
Create Date: 2025-07-28 14:52:36.353887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0520308b8c6d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=True)
    op.create_table('hsc_board',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hsc_board_name'), 'hsc_board', ['name'], unique=True)
    op.create_table('programs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('programe', sa.String(length=100), nullable=False),
    sa.Column('programe_code', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('programe_code')
    )
    op.create_index(op.f('ix_programs_programe'), 'programs', ['programe'], unique=True)
    op.create_table('ssc_board',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ssc_board_name'), 'ssc_board', ['name'], unique=True)
    op.create_table('lookup_master',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=10), nullable=False),
    sa.Column('values', sa.String(length=255), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lookup_master_category_id'), 'lookup_master', ['category_id'], unique=False)
    op.create_index(op.f('ix_lookup_master_key'), 'lookup_master', ['key'], unique=True)
    op.create_table('students',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('application_no', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=10), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('blood_group', sa.String(length=10), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('mobile_number', sa.String(length=15), nullable=False),
    sa.Column('alternative_phone', sa.String(length=15), nullable=True),
    sa.Column('whatsapp_number', sa.String(length=15), nullable=False),
    sa.Column('marital_status', sa.String(length=10), nullable=False),
    sa.Column('religion', sa.String(length=10), nullable=False),
    sa.Column('nationality', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=10), nullable=False),
    sa.Column('caste', sa.String(length=50), nullable=True),
    sa.Column('aadhaar_number', sa.String(length=12), nullable=True),
    sa.Column('pan_number', sa.String(length=10), nullable=True),
    sa.Column('parent_guardian_name', sa.String(length=10), nullable=False),
    sa.Column('relationship_with_student', sa.String(length=50), nullable=False),
    sa.Column('current_employment', sa.String(length=10), nullable=True),
    sa.Column('annual_income', sa.String(length=10), nullable=True),
    sa.Column('locality', sa.String(length=10), nullable=True),
    sa.Column('passport_issued_country', sa.Integer(), nullable=True),
    sa.Column('passport_number', sa.String(length=20), nullable=True),
    sa.Column('passport_expiry_date', sa.Date(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("aadhaar_number ~ '^[0-9]{12}$' ", name='check_aadhaar_format'),
    sa.CheckConstraint("date_of_birth <= current_date - interval '18 years'", name='age_check'),
    sa.CheckConstraint("pan_number ~ '^[A-Z]{5}[0-9]{4}[A-Z]$' ", name='check_pan_format'),
    sa.ForeignKeyConstraint(['nationality'], ['countries.id'], ),
    sa.ForeignKeyConstraint(['passport_issued_country'], ['countries.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aadhaar_number'),
    sa.UniqueConstraint('application_no'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('mobile_number'),
    sa.UniqueConstraint('pan_number')
    )
    op.create_index('ix_students_aadhaar', 'students', ['aadhaar_number'], unique=False)
    op.create_index('ix_students_pan', 'students', ['pan_number'], unique=False)
    op.create_index('ix_students_phone', 'students', ['mobile_number'], unique=False)
    op.create_table('academic_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('ssc_board_id', sa.Integer(), nullable=True),
    sa.Column('ssc_school', sa.String(length=100), nullable=False),
    sa.Column('ssc_scheme', sa.String(length=30), nullable=False),
    sa.Column('ssc_score', sa.String(length=10), nullable=False),
    sa.Column('ssc_year', sa.Date(), nullable=False),
    sa.Column('after_ssc', sa.String(length=20), nullable=False),
    sa.Column('hsc_board_id', sa.Integer(), nullable=True),
    sa.Column('hsc_school', sa.String(length=100), nullable=False),
    sa.Column('hsc_result', sa.String(length=20), nullable=False),
    sa.Column('hsc_scheme', sa.String(length=30), nullable=False),
    sa.Column('hsc_score', sa.String(length=10), nullable=False),
    sa.Column('hsc_year', sa.Date(), nullable=False),
    sa.Column('diploma_institute', sa.String(length=100), nullable=False),
    sa.Column('diploma_board', sa.String(length=100), nullable=False),
    sa.Column('diploma_result', sa.String(length=20), nullable=False),
    sa.Column('diploma_scheme', sa.String(length=30), nullable=False),
    sa.Column('diploma_score', sa.String(length=10), nullable=False),
    sa.Column('diploma_year', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['hsc_board_id'], ['hsc_board.id'], ),
    sa.ForeignKeyConstraint(['ssc_board_id'], ['ssc_board.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id')
    )
    op.create_table('address_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('perm_addr1', sa.String(length=100), nullable=False),
    sa.Column('perm_addr2', sa.String(length=100), nullable=True),
    sa.Column('perm_city', sa.String(length=10), nullable=False),
    sa.Column('perm_state', sa.String(length=10), nullable=False),
    sa.Column('perm_country', sa.Integer(), nullable=False),
    sa.Column('perm_pin', sa.String(length=10), nullable=False),
    sa.Column('corr_addr_same', sa.Boolean(), nullable=True),
    sa.Column('corr_addr1', sa.String(length=100), nullable=True),
    sa.Column('corr_addr2', sa.String(length=100), nullable=True),
    sa.Column('corr_city', sa.String(length=10), nullable=True),
    sa.Column('corr_state', sa.String(length=10), nullable=True),
    sa.Column('corr_country', sa.Integer(), nullable=False),
    sa.Column('corr_pin', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['corr_country'], ['countries.id'], ),
    sa.ForeignKeyConstraint(['perm_country'], ['countries.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id')
    )
    op.create_table('deb_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('deb_id', sa.String(length=80), nullable=False),
    sa.Column('deb_name', sa.String(), nullable=True),
    sa.Column('deb_gender', sa.String(), nullable=True),
    sa.Column('deb_date_of_birth', sa.String(), nullable=True),
    sa.Column('deb_university', sa.String(), nullable=True),
    sa.Column('deb_program', sa.String(), nullable=True),
    sa.Column('deb_abcid', sa.String(), nullable=True),
    sa.Column('deb_details_1', sa.String(), nullable=True),
    sa.Column('deb_details_2', sa.String(), nullable=True),
    sa.Column('deb_details_3', sa.String(), nullable=True),
    sa.Column('deb_details_4', sa.String(), nullable=True),
    sa.Column('deb_details_5', sa.String(), nullable=True),
    sa.Column('deb_details_6', sa.String(), nullable=True),
    sa.Column('deb_details_7', sa.String(), nullable=True),
    sa.Column('deb_details_8', sa.String(), nullable=True),
    sa.Column('deb_details_9', sa.String(), nullable=True),
    sa.Column('deb_details_10', sa.String(), nullable=True),
    sa.Column('deb_details_11', sa.String(), nullable=True),
    sa.Column('deb_details_12', sa.String(), nullable=True),
    sa.Column('deb_details_13', sa.String(), nullable=True),
    sa.Column('deb_details_14', sa.String(), nullable=True),
    sa.Column('deb_details_15', sa.String(), nullable=True),
    sa.Column('deb_status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id')
    )
    op.create_table('declaration_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('declaration_agreed', sa.Boolean(), nullable=False),
    sa.Column('applicant_name', sa.String(length=100), nullable=False),
    sa.Column('parent_name', sa.String(length=100), nullable=True),
    sa.Column('declaration_date', sa.Date(), nullable=False),
    sa.Column('place', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id')
    )
    op.create_table('document_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('class_10th_marksheet', sa.String(length=255), nullable=True),
    sa.Column('class_12th_marksheet', sa.String(length=255), nullable=True),
    sa.Column('graduation_marksheet', sa.String(length=255), nullable=True),
    sa.Column('diploma_marksheet', sa.String(length=255), nullable=True),
    sa.Column('work_experience_certificates', sa.String(length=255), nullable=True),
    sa.Column('passport', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document_details')
    op.drop_table('declaration_details')
    op.drop_table('deb_details')
    op.drop_table('address_details')
    op.drop_table('academic_details')
    op.drop_index('ix_students_phone', table_name='students')
    op.drop_index('ix_students_pan', table_name='students')
    op.drop_index('ix_students_aadhaar', table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_lookup_master_key'), table_name='lookup_master')
    op.drop_index(op.f('ix_lookup_master_category_id'), table_name='lookup_master')
    op.drop_table('lookup_master')
    op.drop_index(op.f('ix_ssc_board_name'), table_name='ssc_board')
    op.drop_table('ssc_board')
    op.drop_index(op.f('ix_programs_programe'), table_name='programs')
    op.drop_table('programs')
    op.drop_index(op.f('ix_hsc_board_name'), table_name='hsc_board')
    op.drop_table('hsc_board')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
