"""re modified course and semester table

Revision ID: 0bbd1a3f4f4c
Revises: 7d3647901a64
Create Date: 2026-02-09 13:05:54.548320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0bbd1a3f4f4c'
down_revision: Union[str, None] = '7d3647901a64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_table('documents')
    op.add_column('student_course_registrations', sa.Column('student_exam_registration_id', sa.Integer(), nullable=False))
    op.add_column('student_course_registrations', sa.Column('component_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('uq_student_course_exam'), 'student_course_registrations', type_='unique')
    op.create_unique_constraint('uq_student_exam_course', 'student_course_registrations', ['student_exam_registration_id', 'course_id'])
    op.drop_constraint(op.f('student_course_registrations_student_id_fkey'), 'student_course_registrations', type_='foreignkey')
    op.drop_constraint(op.f('student_course_registrations_exam_id_fkey'), 'student_course_registrations', type_='foreignkey')
    op.create_foreign_key(None, 'student_course_registrations', 'course_components', ['component_id'], ['id'])
    op.create_foreign_key(None, 'student_course_registrations', 'student_exam_registrations', ['student_exam_registration_id'], ['id'])
    op.drop_column('student_course_registrations', 'student_id')
    op.drop_column('student_course_registrations', 'exam_id')
    op.add_column('student_exam_registrations', sa.Column('scheme_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'student_exam_registrations', 'schemes', ['scheme_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student_exam_registrations', type_='foreignkey')
    op.drop_column('student_exam_registrations', 'scheme_id')
    op.add_column('student_course_registrations', sa.Column('exam_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('student_course_registrations', sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'student_course_registrations', type_='foreignkey')
    op.drop_constraint(None, 'student_course_registrations', type_='foreignkey')
    op.create_foreign_key(op.f('student_course_registrations_exam_id_fkey'), 'student_course_registrations', 'exams', ['exam_id'], ['id'])
    op.create_foreign_key(op.f('student_course_registrations_student_id_fkey'), 'student_course_registrations', 'students', ['student_id'], ['id'])
    op.drop_constraint('uq_student_exam_course', 'student_course_registrations', type_='unique')
    op.create_unique_constraint(op.f('uq_student_course_exam'), 'student_course_registrations', ['student_id', 'exam_id', 'course_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('student_course_registrations', 'component_id')
    op.drop_column('student_course_registrations', 'student_exam_registration_id')
    op.create_table('documents',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('file_url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('uploaded_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('documents_pkey'))
    )
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    # ### end Alembic commands ###
