"""recheck third the student table

Revision ID: 1d36baff7e25
Revises: 87b38a16ca40
Create Date: 2025-08-01 15:18:13.924777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d36baff7e25'
down_revision: Union[str, None] = '87b38a16ca40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('students_nationality_fkey'), 'students', type_='foreignkey')
    op.drop_column('students', 'nationality')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('nationality', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('students_nationality_fkey'), 'students', 'countries', ['nationality'], ['id'])
    # ### end Alembic commands ###
