"""recheck student table

Revision ID: 27c743668527
Revises: c37e70cb2f00
Create Date: 2025-08-01 15:50:58.531125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27c743668527'
down_revision: Union[str, None] = 'c37e70cb2f00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('students', 'nationality',
    #            existing_type=sa.INTEGER(),
    #            type_=sa.String(length=10),
    #            existing_nullable=False)
    op.drop_constraint(op.f('students_nationality_fkey'), 'students', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('students_nationality_fkey'), 'students', 'countries', ['nationality'], ['id'])
    op.alter_column('students', 'nationality',
               existing_type=sa.String(length=10),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
