"""alter student model address table

Revision ID: 4cd1eadde912
Revises: 0520308b8c6d
Create Date: 2025-07-29 09:08:27.561761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cd1eadde912'
down_revision: Union[str, None] = '0520308b8c6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address_details', sa.Column('corr_district', sa.String(length=10), nullable=False))
    op.add_column('address_details', sa.Column('perm_district', sa.String(length=10), nullable=True))
    op.alter_column('address_details', 'corr_addr1',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('address_details', 'corr_city',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('address_details', 'corr_state',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('address_details', 'corr_pin',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('address_details', 'perm_addr1',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('address_details', 'perm_city',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('address_details', 'perm_state',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('address_details', 'perm_country',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('address_details', 'perm_pin',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('address_details', 'perm_pin',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('address_details', 'perm_country',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('address_details', 'perm_state',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('address_details', 'perm_city',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('address_details', 'perm_addr1',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('address_details', 'corr_pin',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('address_details', 'corr_state',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('address_details', 'corr_city',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('address_details', 'corr_addr1',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('address_details', 'perm_district')
    op.drop_column('address_details', 'corr_district')
    # ### end Alembic commands ###
