"""re Initial migration

Revision ID: 5191d4d459e5
Revises: 74d4f68c6b55
Create Date: 2026-01-29 13:04:47.657544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5191d4d459e5'
down_revision: Union[str, None] = '74d4f68c6b55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('programe_id', sa.Integer(), nullable=True),
    sa.Column('course_code_id', sa.Integer(), nullable=False),
    sa.Column('course_category_id', sa.Integer(), nullable=False),
    sa.Column('course_title_id', sa.Integer(), nullable=False),
    sa.Column('semester', sa.String(length=50), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('tutorial_hours', sa.Integer(), nullable=True),
    sa.Column('lecture_hours', sa.Integer(), nullable=True),
    sa.Column('practical_hours', sa.Integer(), nullable=True),
    sa.Column('total_hours', sa.Integer(), nullable=True),
    sa.Column('cia', sa.Integer(), nullable=True),
    sa.Column('esa', sa.Integer(), nullable=True),
    sa.Column('total_marks', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_category_id'], ['course_category.id'], ),
    sa.ForeignKeyConstraint(['course_code_id'], ['course_code.id'], ),
    sa.ForeignKeyConstraint(['course_title_id'], ['course_title.id'], ),
    sa.ForeignKeyConstraint(['programe_id'], ['programs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subjects_course_category_id'), 'subjects', ['course_category_id'], unique=False)
    op.create_index(op.f('ix_subjects_course_code_id'), 'subjects', ['course_code_id'], unique=False)
    op.create_index(op.f('ix_subjects_course_title_id'), 'subjects', ['course_title_id'], unique=False)
    op.create_index(op.f('ix_subjects_programe_id'), 'subjects', ['programe_id'], unique=False)
    op.create_index(op.f('ix_subjects_semester'), 'subjects', ['semester'], unique=False)
    op.drop_index(op.f('ix_semester_syllabus_course_category_id'), table_name='semester_syllabus')
    op.drop_index(op.f('ix_semester_syllabus_course_code_id'), table_name='semester_syllabus')
    op.drop_index(op.f('ix_semester_syllabus_course_title_id'), table_name='semester_syllabus')
    op.drop_index(op.f('ix_semester_syllabus_semester'), table_name='semester_syllabus')
    op.drop_table('semester_syllabus')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_table('documents')
    op.alter_column('address_details', 'perm_country',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.add_column('programs', sa.Column('batch', sa.String(length=10), nullable=True))
    op.add_column('programs', sa.Column('admission_year', sa.String(length=10), nullable=True))
    op.add_column('students', sa.Column('batch', sa.String(length=10), nullable=True))
    op.add_column('students', sa.Column('admission_year', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'admission_year')
    op.drop_column('students', 'batch')
    op.drop_column('programs', 'admission_year')
    op.drop_column('programs', 'batch')
    op.alter_column('address_details', 'perm_country',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.create_table('documents',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('file_url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('uploaded_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('documents_pkey'))
    )
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_table('semester_syllabus',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('course_code_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('course_category_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('course_title_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('semester', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('credits', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tutorial_hours', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lecture_hours', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('practical_hours', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_hours', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cia', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('esa', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_marks', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['course_category_id'], ['course_category.id'], name=op.f('semester_syllabus_course_category_id_fkey')),
    sa.ForeignKeyConstraint(['course_code_id'], ['course_code.id'], name=op.f('semester_syllabus_course_code_id_fkey')),
    sa.ForeignKeyConstraint(['course_title_id'], ['course_title.id'], name=op.f('semester_syllabus_course_title_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('semester_syllabus_pkey'))
    )
    op.create_index(op.f('ix_semester_syllabus_semester'), 'semester_syllabus', ['semester'], unique=False)
    op.create_index(op.f('ix_semester_syllabus_course_title_id'), 'semester_syllabus', ['course_title_id'], unique=False)
    op.create_index(op.f('ix_semester_syllabus_course_code_id'), 'semester_syllabus', ['course_code_id'], unique=False)
    op.create_index(op.f('ix_semester_syllabus_course_category_id'), 'semester_syllabus', ['course_category_id'], unique=False)
    op.drop_index(op.f('ix_subjects_semester'), table_name='subjects')
    op.drop_index(op.f('ix_subjects_programe_id'), table_name='subjects')
    op.drop_index(op.f('ix_subjects_course_title_id'), table_name='subjects')
    op.drop_index(op.f('ix_subjects_course_code_id'), table_name='subjects')
    op.drop_index(op.f('ix_subjects_course_category_id'), table_name='subjects')
    op.drop_table('subjects')
    # ### end Alembic commands ###
