"""update field student table

Revision ID: 5d5d30a54ac6
Revises: a4b859eb9439
Create Date: 2025-08-04 12:28:34.546533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d5d30a54ac6'
down_revision: Union[str, None] = 'a4b859eb9439'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('registration_no', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'students', ['registration_no'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='unique')
    op.drop_column('students', 'registration_no')
    # ### end Alembic commands ###
