"""alter student model table

Revision ID: 722b0100a8a9
Revises: 4cd1eadde912
Create Date: 2025-07-29 11:24:25.565850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '722b0100a8a9'
down_revision: Union[str, None] = '4cd1eadde912'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_details', sa.Column('aadhar', sa.String(length=255), nullable=True))
    op.add_column('document_details', sa.Column('signature', sa.String(length=255), nullable=True))
    op.alter_column('students', 'parent_guardian_name',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('students', 'current_employment',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=100),
               existing_nullable=True)
    # Use explicit cast for annual_income
    op.execute('ALTER TABLE students ALTER COLUMN annual_income TYPE INTEGER USING annual_income::integer;')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'annual_income',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('students', 'current_employment',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('students', 'parent_guardian_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.drop_column('document_details', 'signature')
    op.drop_column('document_details', 'aadhar')
    # ### end Alembic commands ###
