"""modify Exam tables

Revision ID: 72e983d9a8f2
Revises: 5493eb6a2591
Create Date: 2026-02-07 11:47:19.481582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '72e983d9a8f2'
down_revision: Union[str, None] = '5493eb6a2591'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_constraint(op.f('exams_semester_id_fkey'), 'exams', type_='foreignkey')
    op.drop_constraint(op.f('exams_batch_id_fkey'), 'exams', type_='foreignkey')
    op.drop_column('exams', 'semester_id')
    op.drop_column('exams', 'batch_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exams', sa.Column('batch_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('exams', sa.Column('semester_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('exams_batch_id_fkey'), 'exams', 'batches', ['batch_id'], ['id'])
    op.create_foreign_key(op.f('exams_semester_id_fkey'), 'exams', 'semesters', ['semester_id'], ['id'])
    op.create_table('documents',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('file_url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('uploaded_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('documents_pkey'))
    )
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    # ### end Alembic commands ###
