"""initial migrations

Revision ID: 74d4f68c6b55
Revises: 
Create Date: 2025-12-26 15:02:31.873537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74d4f68c6b55'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=True)
    op.create_table('countries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('country_code', sa.String(length=5), nullable=False),
    sa.Column('phone_code', sa.String(length=5), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_countries_name'), 'countries', ['name'], unique=True)
    op.create_table('course_category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_category_name'), 'course_category', ['name'], unique=True)
    op.create_table('course_code',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_code_code'), 'course_code', ['code'], unique=True)
    op.create_table('course_title',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_title_title'), 'course_title', ['title'], unique=True)
    op.create_table('groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_groups_id'), 'groups', ['id'], unique=False)
    op.create_table('hsc_board',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hsc_board_name'), 'hsc_board', ['name'], unique=True)
    op.create_table('menus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('to', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_menus_id'), 'menus', ['id'], unique=False)
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codename', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codename')
    )
    op.create_table('programs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('programe', sa.String(length=100), nullable=False),
    sa.Column('short_name', sa.String(length=20), nullable=True),
    sa.Column('programe_code', sa.String(length=50), nullable=False),
    sa.Column('duration', sa.String(length=20), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('faculty', sa.String(length=100), nullable=True),
    sa.Column('application_code', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('programe_code')
    )
    op.create_index(op.f('ix_programs_programe'), 'programs', ['programe'], unique=True)
    op.create_table('ssc_board',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ssc_board_name'), 'ssc_board', ['name'], unique=True)
    op.create_table('fee_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('programe_id', sa.Integer(), nullable=True),
    sa.Column('semester', sa.String(), nullable=True),
    sa.Column('application_fee', sa.String(), nullable=True),
    sa.Column('admission_fee', sa.String(), nullable=True),
    sa.Column('tuition_fee', sa.String(), nullable=True),
    sa.Column('exam_fee', sa.String(), nullable=True),
    sa.Column('lms_fee', sa.String(), nullable=True),
    sa.Column('lab_fee', sa.String(), nullable=True),
    sa.Column('total_fee', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['programe_id'], ['programs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fee_details_id'), 'fee_details', ['id'], unique=False)
    op.create_table('group_permission',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.PrimaryKeyConstraint('group_id', 'permission_id')
    )
    op.create_table('lookup_master',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=10), nullable=False),
    sa.Column('values', sa.String(length=255), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lookup_master_category_id'), 'lookup_master', ['category_id'], unique=False)
    op.create_index(op.f('ix_lookup_master_key'), 'lookup_master', ['key'], unique=True)
    op.create_table('semester_syllabus',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('course_code_id', sa.Integer(), nullable=False),
    sa.Column('course_category_id', sa.Integer(), nullable=False),
    sa.Column('course_title_id', sa.Integer(), nullable=False),
    sa.Column('semester', sa.String(length=50), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('tutorial_hours', sa.Integer(), nullable=True),
    sa.Column('lecture_hours', sa.Integer(), nullable=True),
    sa.Column('practical_hours', sa.Integer(), nullable=True),
    sa.Column('total_hours', sa.Integer(), nullable=True),
    sa.Column('cia', sa.Integer(), nullable=True),
    sa.Column('esa', sa.Integer(), nullable=True),
    sa.Column('total_marks', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_category_id'], ['course_category.id'], ),
    sa.ForeignKeyConstraint(['course_code_id'], ['course_code.id'], ),
    sa.ForeignKeyConstraint(['course_title_id'], ['course_title.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_semester_syllabus_course_category_id'), 'semester_syllabus', ['course_category_id'], unique=False)
    op.create_index(op.f('ix_semester_syllabus_course_code_id'), 'semester_syllabus', ['course_code_id'], unique=False)
    op.create_index(op.f('ix_semester_syllabus_course_title_id'), 'semester_syllabus', ['course_title_id'], unique=False)
    op.create_index(op.f('ix_semester_syllabus_semester'), 'semester_syllabus', ['semester'], unique=False)
    op.create_table('states',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_states_name'), 'states', ['name'], unique=False)
    op.create_table('students',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('application_no', sa.String(length=20), nullable=True),
    sa.Column('registration_no', sa.String(), nullable=True),
    sa.Column('title', sa.String(length=10), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('blood_group', sa.String(length=10), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('mobile_number', sa.String(length=15), nullable=False),
    sa.Column('alternative_phone', sa.String(length=15), nullable=True),
    sa.Column('whatsapp_number', sa.String(length=15), nullable=False),
    sa.Column('marital_status', sa.String(length=10), nullable=False),
    sa.Column('religion', sa.String(length=20), nullable=False),
    sa.Column('nationality', sa.String(length=30), nullable=False),
    sa.Column('category', sa.String(length=10), nullable=False),
    sa.Column('caste', sa.String(length=50), nullable=True),
    sa.Column('aadhaar_number', sa.String(length=12), nullable=True),
    sa.Column('pan_number', sa.String(length=10), nullable=True),
    sa.Column('parent_guardian_name', sa.String(length=100), nullable=False),
    sa.Column('relationship_with_student', sa.String(length=50), nullable=False),
    sa.Column('current_employment', sa.String(length=100), nullable=True),
    sa.Column('annual_income', sa.String(length=20), nullable=True),
    sa.Column('locality', sa.String(length=10), nullable=True),
    sa.Column('passport_issued_country', sa.String(length=30), nullable=True),
    sa.Column('passport_number', sa.String(length=20), nullable=True),
    sa.Column('passport_expiry_date', sa.Date(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('is_pushed', sa.Boolean(), nullable=True),
    sa.Column('is_pushed_digi', sa.Boolean(), nullable=True),
    sa.Column('is_synced', sa.Boolean(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("aadhaar_number ~ '^[0-9]{12}$' ", name='check_aadhaar_format'),
    sa.CheckConstraint("date_of_birth <= current_date - interval '18 years'", name='age_check'),
    sa.CheckConstraint("pan_number ~ '^[A-Z]{5}[0-9]{4}[A-Z]$' ", name='check_pan_format'),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aadhaar_number'),
    sa.UniqueConstraint('application_no'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('mobile_number'),
    sa.UniqueConstraint('pan_number'),
    sa.UniqueConstraint('registration_no')
    )
    op.create_index('ix_students_aadhaar', 'students', ['aadhaar_number'], unique=False)
    op.create_index('ix_students_pan', 'students', ['pan_number'], unique=False)
    op.create_index('ix_students_phone', 'students', ['mobile_number'], unique=False)
    op.create_table('submenus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('menu_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('to', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['menu_id'], ['menus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submenus_id'), 'submenus', ['id'], unique=False)
    op.create_table('academic_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('ssc_board_id', sa.Integer(), nullable=True),
    sa.Column('ssc_school', sa.String(length=100), nullable=False),
    sa.Column('ssc_scheme', sa.String(length=30), nullable=False),
    sa.Column('ssc_score', sa.String(length=10), nullable=False),
    sa.Column('ssc_year', sa.Date(), nullable=False),
    sa.Column('after_ssc', sa.String(length=20), nullable=False),
    sa.Column('hsc_board_id', sa.Integer(), nullable=True),
    sa.Column('hsc_school', sa.String(length=100), nullable=True),
    sa.Column('hsc_result', sa.String(length=20), nullable=True),
    sa.Column('hsc_scheme', sa.String(length=30), nullable=True),
    sa.Column('hsc_score', sa.String(length=10), nullable=True),
    sa.Column('hsc_year', sa.Date(), nullable=True),
    sa.Column('diploma_institute', sa.String(length=100), nullable=False),
    sa.Column('diploma_board', sa.String(length=100), nullable=False),
    sa.Column('diploma_result', sa.String(length=20), nullable=False),
    sa.Column('diploma_scheme', sa.String(length=30), nullable=False),
    sa.Column('diploma_score', sa.String(length=10), nullable=False),
    sa.Column('diploma_year', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['hsc_board_id'], ['hsc_board.id'], ),
    sa.ForeignKeyConstraint(['ssc_board_id'], ['ssc_board.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id')
    )
    op.create_table('address_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('corr_addr1', sa.String(length=100), nullable=False),
    sa.Column('corr_addr2', sa.String(length=100), nullable=True),
    sa.Column('corr_city', sa.String(length=30), nullable=True),
    sa.Column('corr_state', sa.String(length=30), nullable=True),
    sa.Column('corr_district', sa.String(length=30), nullable=True),
    sa.Column('corr_country', sa.String(length=30), nullable=False),
    sa.Column('corr_pin', sa.String(length=10), nullable=False),
    sa.Column('corr_addr_same', sa.Boolean(), nullable=True),
    sa.Column('perm_addr1', sa.String(length=100), nullable=True),
    sa.Column('perm_addr2', sa.String(length=100), nullable=True),
    sa.Column('perm_city', sa.String(length=30), nullable=True),
    sa.Column('perm_state', sa.String(length=30), nullable=True),
    sa.Column('perm_district', sa.String(length=30), nullable=True),
    sa.Column('perm_country', sa.String(length=30), nullable=False),
    sa.Column('perm_pin', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id')
    )
    op.create_table('city',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('city_name', sa.String(length=100), nullable=False),
    sa.Column('state_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deb_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('deb_id', sa.String(length=80), nullable=False),
    sa.Column('deb_name', sa.String(), nullable=True),
    sa.Column('deb_gender', sa.String(), nullable=True),
    sa.Column('deb_date_of_birth', sa.String(), nullable=True),
    sa.Column('deb_university', sa.String(), nullable=True),
    sa.Column('deb_program', sa.String(), nullable=True),
    sa.Column('deb_abcid', sa.String(), nullable=True),
    sa.Column('deb_details_1', sa.String(), nullable=True),
    sa.Column('deb_details_2', sa.String(), nullable=True),
    sa.Column('deb_details_3', sa.String(), nullable=True),
    sa.Column('deb_details_4', sa.String(), nullable=True),
    sa.Column('deb_details_5', sa.String(), nullable=True),
    sa.Column('deb_details_6', sa.String(), nullable=True),
    sa.Column('deb_details_7', sa.String(), nullable=True),
    sa.Column('deb_details_8', sa.String(), nullable=True),
    sa.Column('deb_details_9', sa.String(), nullable=True),
    sa.Column('deb_details_10', sa.String(), nullable=True),
    sa.Column('deb_details_11', sa.String(), nullable=True),
    sa.Column('deb_details_12', sa.String(), nullable=True),
    sa.Column('deb_details_13', sa.String(), nullable=True),
    sa.Column('deb_details_14', sa.String(), nullable=True),
    sa.Column('deb_details_15', sa.String(), nullable=True),
    sa.Column('deb_status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id')
    )
    op.create_table('declaration_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('declaration_agreed', sa.Boolean(), nullable=False),
    sa.Column('applicant_name', sa.String(length=100), nullable=False),
    sa.Column('parent_name', sa.String(length=100), nullable=True),
    sa.Column('declaration_date', sa.Date(), nullable=False),
    sa.Column('place', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id')
    )
    op.create_table('district',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('district_name', sa.String(length=100), nullable=False),
    sa.Column('state_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_district_id'), 'district', ['id'], unique=False)
    op.create_table('document_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('class_10th_marksheet', sa.Text(), nullable=True),
    sa.Column('class_12th_marksheet', sa.Text(), nullable=True),
    sa.Column('graduation_marksheet', sa.Text(), nullable=True),
    sa.Column('diploma_marksheet', sa.Text(), nullable=True),
    sa.Column('work_experience_certificates', sa.Text(), nullable=True),
    sa.Column('passport', sa.Text(), nullable=True),
    sa.Column('aadhar', sa.Text(), nullable=True),
    sa.Column('signature', sa.Text(), nullable=True),
    sa.Column('profile_image', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id')
    )
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('payment_type', sa.String(length=50), nullable=True),
    sa.Column('order_id', sa.String(length=50), nullable=True),
    sa.Column('transaction_id', sa.String(length=50), nullable=True),
    sa.Column('payment_date', sa.DateTime(), nullable=True),
    sa.Column('payment_amount', sa.Float(), nullable=True),
    sa.Column('is_offline', sa.Boolean(), nullable=True),
    sa.Column('offline_transaction_id', sa.String(length=50), nullable=True),
    sa.Column('offline_payment_method', sa.String(length=50), nullable=True),
    sa.Column('offline_receipt_enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('student_id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address_line1', sa.String(length=100), nullable=False),
    sa.Column('address_line2', sa.String(length=100), nullable=True),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('state_id', sa.Integer(), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('postal_code', sa.String(length=20), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], ),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.ForeignKeyConstraint(['district_id'], ['district.id'], ),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('application_fees',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_id')
    )
    op.create_table('semester_fees',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.Column('semester', sa.String(length=20), nullable=True),
    sa.Column('admission_fee', sa.Float(), nullable=True),
    sa.Column('lab_fee', sa.Float(), nullable=True),
    sa.Column('lms_fee', sa.Float(), nullable=True),
    sa.Column('exam_fee', sa.Float(), nullable=True),
    sa.Column('tuition_fee', sa.Float(), nullable=True),
    sa.Column('total_fee', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_id')
    )
    op.create_table('staff',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('designation', sa.String(length=100), nullable=True),
    sa.Column('qualification', sa.String(length=150), nullable=True),
    sa.Column('specialization', sa.String(length=150), nullable=True),
    sa.Column('joining_date', sa.Date(), nullable=True),
    sa.Column('experience_years', sa.Float(), nullable=True),
    sa.Column('employment_type', sa.Enum('internal', 'external', 'permanent', name='employmenttypeenum'), nullable=False),
    sa.Column('research_area', sa.Text(), nullable=True),
    sa.Column('publications_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', 'retired', name='facultystatusenum'), nullable=False),
    sa.Column('linkedin_url', sa.String(length=200), nullable=True),
    sa.Column('profile_photo', sa.String(length=200), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('employee_id'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_staff_id'), 'staff', ['id'], unique=False)
    op.create_table('user_group',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'group_id')
    )
    op.create_table('user_permission',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'permission_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_permission')
    op.drop_table('user_group')
    op.drop_index(op.f('ix_staff_id'), table_name='staff')
    op.drop_table('staff')
    op.drop_table('semester_fees')
    op.drop_table('application_fees')
    op.drop_table('address')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('payments')
    op.drop_table('document_details')
    op.drop_index(op.f('ix_district_id'), table_name='district')
    op.drop_table('district')
    op.drop_table('declaration_details')
    op.drop_table('deb_details')
    op.drop_table('city')
    op.drop_table('address_details')
    op.drop_table('academic_details')
    op.drop_index(op.f('ix_submenus_id'), table_name='submenus')
    op.drop_table('submenus')
    op.drop_index('ix_students_phone', table_name='students')
    op.drop_index('ix_students_pan', table_name='students')
    op.drop_index('ix_students_aadhaar', table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_states_name'), table_name='states')
    op.drop_table('states')
    op.drop_index(op.f('ix_semester_syllabus_semester'), table_name='semester_syllabus')
    op.drop_index(op.f('ix_semester_syllabus_course_title_id'), table_name='semester_syllabus')
    op.drop_index(op.f('ix_semester_syllabus_course_code_id'), table_name='semester_syllabus')
    op.drop_index(op.f('ix_semester_syllabus_course_category_id'), table_name='semester_syllabus')
    op.drop_table('semester_syllabus')
    op.drop_index(op.f('ix_lookup_master_key'), table_name='lookup_master')
    op.drop_index(op.f('ix_lookup_master_category_id'), table_name='lookup_master')
    op.drop_table('lookup_master')
    op.drop_table('group_permission')
    op.drop_index(op.f('ix_fee_details_id'), table_name='fee_details')
    op.drop_table('fee_details')
    op.drop_index(op.f('ix_ssc_board_name'), table_name='ssc_board')
    op.drop_table('ssc_board')
    op.drop_index(op.f('ix_programs_programe'), table_name='programs')
    op.drop_table('programs')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_menus_id'), table_name='menus')
    op.drop_table('menus')
    op.drop_index(op.f('ix_hsc_board_name'), table_name='hsc_board')
    op.drop_table('hsc_board')
    op.drop_index(op.f('ix_groups_id'), table_name='groups')
    op.drop_table('groups')
    op.drop_index(op.f('ix_course_title_title'), table_name='course_title')
    op.drop_table('course_title')
    op.drop_index(op.f('ix_course_code_code'), table_name='course_code')
    op.drop_table('course_code')
    op.drop_index(op.f('ix_course_category_name'), table_name='course_category')
    op.drop_table('course_category')
    op.drop_index(op.f('ix_countries_name'), table_name='countries')
    op.drop_table('countries')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
