"""update the staff table

Revision ID: 85d3b71965e0
Revises: a080f871c5af
Create Date: 2026-01-29 13:39:10.373652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '85d3b71965e0'
down_revision: Union[str, None] = 'a080f871c5af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_table('documents')
    op.add_column('staff', sa.Column('department_id', sa.Integer(), nullable=True))
    op.alter_column('staff', 'phone',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)
    op.alter_column('staff', 'role',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.create_foreign_key(None, 'staff', 'departments', ['department_id'], ['id'])
    op.drop_column('staff', 'linkedin_url')
    op.drop_column('staff', 'publications_count')
    op.drop_column('staff', 'research_area')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff', sa.Column('research_area', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('staff', sa.Column('publications_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('staff', sa.Column('linkedin_url', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'staff', type_='foreignkey')
    op.alter_column('staff', 'role',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('staff', 'phone',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)
    op.drop_column('staff', 'department_id')
    op.create_table('documents',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('file_url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('uploaded_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('documents_pkey'))
    )
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    # ### end Alembic commands ###
