"""remoed columns

Revision ID: 970843b5ccd5
Revises: c89ab28217cf
Create Date: 2026-04-06 14:06:56.799821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '970843b5ccd5'
down_revision: Union[str, None] = 'c89ab28217cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_keys_api_key'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_id'), table_name='api_keys')
    op.drop_table('api_keys')
    # Add with server default to avoid NOT NULL violation on existing rows, then drop default
    op.add_column(
        'students',
        sa.Column(
            'pending_payment_workflow_enabled',
            sa.Boolean(),
            nullable=False,
            server_default=sa.text('false'),
        ),
    )
    op.alter_column(
        'students',
        'pending_payment_workflow_enabled',
        server_default=None,
    )
    op.drop_index(op.f('ix_students_batch_year_semester'), table_name='students')
    op.drop_column('students', 'pending_payment_semester')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('pending_payment_semester', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_students_batch_year_semester'), 'students', ['batch', 'admission_year', 'semester'], unique=False)
    op.drop_column('students', 'pending_payment_workflow_enabled')
    op.create_table('api_keys',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('client_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('api_key', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('api_keys_pkey'))
    )
    op.create_index(op.f('ix_api_keys_id'), 'api_keys', ['id'], unique=False)
    op.create_index(op.f('ix_api_keys_api_key'), 'api_keys', ['api_key'], unique=True)
    # ### end Alembic commands ###
