"""change the final student table

Revision ID: 993d117008ee
Revises: 722b0100a8a9
Create Date: 2025-07-29 11:46:22.885220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '993d117008ee'
down_revision: Union[str, None] = '722b0100a8a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'annual_income',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=10),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'annual_income',
               existing_type=sa.String(length=10),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
