"""modified the course and semester table

Revision ID: 9de971ff6098
Revises: 0bbd1a3f4f4c
Create Date: 2026-02-09 15:11:36.764995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9de971ff6098'
down_revision: Union[str, None] = '0bbd1a3f4f4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_table('documents')
    op.add_column('student_course_registrations', sa.Column('permitted', sa.Boolean(), nullable=True))
    op.drop_column('student_course_registrations', 'is_appearing')
    op.add_column('student_exam_registrations', sa.Column('is_eligible', sa.Boolean(), nullable=True))
    op.add_column('student_exam_registrations', sa.Column('registered_on', sa.DateTime(), nullable=True))
    op.drop_column('student_exam_registrations', 'is_confirmed')
    op.drop_column('student_exam_registrations', 'hall_ticket_no')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_exam_registrations', sa.Column('hall_ticket_no', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('student_exam_registrations', sa.Column('is_confirmed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('student_exam_registrations', 'registered_on')
    op.drop_column('student_exam_registrations', 'is_eligible')
    op.add_column('student_course_registrations', sa.Column('is_appearing', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('student_course_registrations', 'permitted')
    op.create_table('documents',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('file_url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('uploaded_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('documents_pkey'))
    )
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    # ### end Alembic commands ###
