"""final recheck student table

Revision ID: c37e70cb2f00
Revises: 02de1c9f9c58
Create Date: 2025-08-01 15:47:10.510989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c37e70cb2f00'
down_revision: Union[str, None] = '02de1c9f9c58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('nationality', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'students', 'countries', ['nationality'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_column('students', 'nationality')
    # ### end Alembic commands ###
